### ISSUE TITLE
ev_search only seems to show ~183 tickets. Asking for more breaks it

### ISSUE THREAD

**Issue by matthewsucar** [NCAR/pyextraview#2]
ev_search -d -u nate --days 1000000000 | grep CLOSURE_CODE | uniq -c
    183 HELP_CLOSURE_CODE: Successful

ev_search -d -u ssgev --days 1000000000 --max 100000000 | grep CLOSURE_CODE | uniq -c
matthews@chmgt:~>

**Comment by nateucar** [comment]
Fixed in f7cff9be01f45cdb6d6c113e2a1d971ccab49b30
