### ISSUE TITLE
ev_search should not include closed issues by default 

### ISSUE THREAD

**Issue by matthewsucar** [NCAR/pyextraview#3]
ev_search -d -u nate | grep CLOSURE_CODE | uniq -c
    183 HELP_CLOSURE_CODE: Successful

Generally, only open (or "assigned" in EV lingo) tickets are useful.

**Comment by ncaroberts** [comment]
Updated extraview/cli.py with fix

**Comment by nateucar** [comment]
Fixed by https://github.com/NCAR/pyextraview/commit/5f6facf79ee5f6a402ba646ce59db9a9be3403f7
